[env:x4_journal]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.flash_size = 4MB
board_build.partitions = partitions.csv
build_flags =
    -DLOG_LOCAL_LEVEL=ESP_LOG_DEBUG
    -I src
lib_deps =
    EInkDisplay=symlink://open-x4-sdk/libs/display/EInkDisplay
    BatteryMonitor=symlink://open-x4-sdk/libs/hardware/BatteryMonitor
    InputManager=symlink://open-x4-sdk/libs/hardware/InputManager
    SDCardManager=symlink://open-x4-sdk/libs/hardware/SDCardManager
    greiman/SdFat@^2.3.1
